name: Release Nucleus CI

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nucleus
  ORG_NAME: northstar-pay

jobs:

  publish-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
            echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/pull/"* ]]; then
            echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          fi

      - name: Setup Docker Image URL
        run: echo "IMAGE_URL=${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Setup Docker Tag
        run: echo "IMAGE_TAG=${{ env.branch_name }}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.IMAGE_URL }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_URL }}:${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_URL }}:latest $(echo ${{ steps.meta.outputs.labels }} | sed 's/,/ --label /g') -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_URL }} --all-tags
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: [publish-docker-image]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd dev/nucleus
            docker compose stop migration
            docker compose stop worker
            docker compose stop server
            docker compose rm -f server worker migration
            docker compose pull server worker migration
            docker compose up -d migration
            docker compose up -d worker
            docker compose up -d server
            exit
      